Added Verifier capability
bcgov/bc-wallet-mobile pull request #1017
Opened 2023-04-02 06:09 UTC by Artemkaaas

2023-04-06 16:15 UTC, jleach commented
@Artemkaaas Able to add a brief description to this PR?

2023-04-12 23:01 UTC, bryce-mcmath approved these changes, later dismissed

2023-04-12 23:08 UTC, jleach requested changes

2023-04-12 23:08 UTC, jleach commented on app/src/constants.ts
I feel like constants.ts isn't the right place for these templates. Can you move them to a `templates.ts` file?

2023-04-13 17:36 UTC, jleach commented
@Artemkaaas Able to make the one change requested and fix conflicts so we can then this one merged.

2023-04-13 18:28 UTC, Artemkaaas commented on app/src/constants.ts
done

2023-04-13 18:28 UTC, Artemkaaas commented
> @Artemkaaas Able to make the one change requested and fix conflicts so we can then this one merged.

Done

2023-04-13 21:33 UTC, jleach commented
@Artemkaaas Looking better. Build failed with the following:

```console
Error: src/index.ts(25,39): error TS2307: Cannot find module './constants' or its corresponding type declarations.
ERROR: "build:app" exited with 2.
ERROR: "build:all" exited with 1.
npm ERR! code 1
npm ERR! path /Users/runner/work/bc-wallet-mobile/bc-wallet-mobile
npm ERR! command failed
npm ERR! command sh -c run-s install:all build:all

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2023-04-13T21_19_29_545Z-debug-0.log
Error: Process completed with exit code 1.
```

2023-04-14 16:05 UTC, jleach approved these changes

2023-04-14 16:06 UTC, bryce-mcmath approved these changes
Nice work!

2023-04-14 16:18 UTC, wadeking98 requested changes

2023-04-14 16:18 UTC, wadeking98 commented on app/src/request-templates.ts
> +              restrictions: [{ schema_id: 'XUxBrVSALWHLeycAUhrNr9:2:Person:1.0' }],
We need to make all the restrictions by credential definition id, not schema id. Anyone can create a credential with a given schema_id, so anyone can issue themselves a credential that passes this proof request.

2023-04-17 16:03 UTC, wadeking98 commented on app/src/request-templates.ts
> +              restrictions: [{ schema_id: 'XUxBrVSALWHLeycAUhrNr9:2:Person:1.0' }],
going to approve this to get it in the codebase, but I'll create a separate issue for changing the restrictions

2023-04-17 16:04 UTC, wadeking98 approved these changes

2023-04-17 16:11 UTC, merged