feat: automatic attestation for person credential
bcgov/bc-wallet-mobile pull request #1868
Opened 2024-03-19 22:26 UTC by jleach

When retrieving a person credentnial app attestation is required. This PR adds mechanics to automatically fetch the attestation credential if it is not present and accept the proof request.

2024-03-22 23:54 UTC, bryce-mcmath requested changes
One initial change requested that we talked about yesterday. Other than that, does this logic handle both situations with the BCSC app? ie. does the person flow work both with and without attestation when attestation support is enabled in the wallet?

2024-03-22 23:54 UTC, bryce-mcmath commented on app/src/helpers/Attestation.ts
> +  }
should this be `!== <the number of attributes on our attestation credentials>`? Should be strict too I think (`!==` not `!=`)

2024-03-23 00:13 UTC, jleach commented
> One initial change requested that we talked about yesterday. Other than that, does this logic handle both situations with the BCSC app? ie. does the person flow work both with and without attestation when attestation support is enabled in the wallet?

The reason for the additional logic is that Credo does not select the newest non-revoked credential which we would like in all situations. I created [this](https://github.com/orgs/bcgov/projects/108?pane=issue&itemId=57285368) to track revisiting the issue to make sure it still persists in Credo 0.4.x and 0.5.x.

The Person workflow does work in both cases although once IDIM has deployed the change they will not issue a Person credential without a correct response to the proof.

2024-03-23 00:13 UTC, jleach commented on app/src/helpers/Attestation.ts
> +  }
Will fix.

2024-03-25 16:30 UTC, jleach commented on app/src/helpers/Attestation.ts
> +  }
@bryce-mcmath I fixed the strict equality check. I think it should still be `===`. That credential will have no attributes if its missing. As part of a more advanced "walk" feature we should experiment to see if the proof is asking for 5 attributes then our fetched credential should have at least 5 attributes. I'm not sure if it works this way which is why I didn't add it now (probably needs a spike.

2024-03-25 16:36 UTC, bryce-mcmath approved these changes

2024-03-25 16:44 UTC, merged